-- CareSense Sepsis Risk Prediction Platform
-- Supabase PostgreSQL Database Schema & Row Level Security (RLS)
-- Version 1.0.0

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles Table (Clinical Personnel & Researchers)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'clinician', 'researcher')),
    hospital_id TEXT NOT NULL DEFAULT 'HOSP-METRO-CENTRAL',
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Patients Table
CREATE TABLE IF NOT EXISTS public.patients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_code TEXT UNIQUE NOT NULL,
    age INT NOT NULL,
    gender TEXT NOT NULL CHECK (gender IN ('M', 'F', 'Other')),
    icu_bed TEXT NOT NULL,
    admission_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'DISCHARGED', 'TRANSFERRED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Patient Vitals (Time-series / temporal measurements)
CREATE TABLE IF NOT EXISTS public.patient_vitals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hr NUMERIC(5, 1),       -- Heart rate (BPM)
    o2sat NUMERIC(4, 1),    -- Oxygen saturation (%)
    temp NUMERIC(4, 1),     -- Body temperature (°C)
    sbp NUMERIC(5, 1),      -- Systolic blood pressure (mmHg)
    map NUMERIC(5, 1),      -- Mean arterial pressure (mmHg)
    dbp NUMERIC(5, 1),      -- Diastolic blood pressure (mmHg)
    resp NUMERIC(4, 1),     -- Respiration rate (breaths/min)
    etco2 NUMERIC(4, 1),    -- End-tidal CO2 (mmHg)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_vitals_patient_time ON public.patient_vitals(patient_id, timestamp DESC);

-- 4. Patient Laboratory Results
CREATE TABLE IF NOT EXISTS public.patient_labs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    base_excess NUMERIC(5, 2),
    hco3 NUMERIC(5, 2),
    fio2 NUMERIC(4, 2),
    ph NUMERIC(4, 2),
    paco2 NUMERIC(5, 2),
    sao2 NUMERIC(4, 1),
    ast NUMERIC(6, 1),
    bun NUMERIC(5, 1),
    alkalinephos NUMERIC(6, 1),
    calcium NUMERIC(4, 1),
    chloride NUMERIC(5, 1),
    creatinine NUMERIC(5, 2),
    bilirubin_direct NUMERIC(4, 2),
    glucose NUMERIC(5, 1),
    lactate NUMERIC(5, 2),
    magnesium NUMERIC(4, 2),
    phosphate NUMERIC(4, 2),
    potassium NUMERIC(4, 2),
    bilirubin_total NUMERIC(4, 2),
    troponini NUMERIC(6, 3),
    hct NUMERIC(4, 1),
    hgb NUMERIC(4, 1),
    ptt NUMERIC(5, 1),
    wbc NUMERIC(5, 2),
    fibrinogen NUMERIC(6, 1),
    platelets NUMERIC(6, 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_labs_patient_time ON public.patient_labs(patient_id, timestamp DESC);

-- 5. Risk Predictions (Generated by CareSense ML Service)
CREATE TABLE IF NOT EXISTS public.risk_predictions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    risk_probability NUMERIC(4, 3) NOT NULL CHECK (risk_probability >= 0 AND risk_probability <= 1),
    risk_tier TEXT NOT NULL CHECK (risk_tier IN ('LOW', 'WATCH', 'ELEVATED', 'CRITICAL')),
    risk_status TEXT NOT NULL DEFAULT 'CALCULATED',
    model_version TEXT NOT NULL DEFAULT 'v1.0.0',
    prediction_horizon TEXT NOT NULL DEFAULT '6H',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_predictions_patient_time ON public.risk_predictions(patient_id, timestamp DESC);

-- 6. Risk Explanations (SHAP Attribution Features)
CREATE TABLE IF NOT EXISTS public.risk_explanations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    prediction_id UUID NOT NULL REFERENCES public.risk_predictions(id) ON DELETE CASCADE,
    feature_name TEXT NOT NULL,
    feature_value TEXT NOT NULL,
    shap_value NUMERIC(6, 4) NOT NULL,
    direction TEXT NOT NULL CHECK (direction IN ('INCREASES_RISK', 'DECREASES_RISK', 'NEUTRAL')),
    rank INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_explanations_prediction ON public.risk_explanations(prediction_id, rank ASC);

-- 7. Alerts Table
CREATE TABLE IF NOT EXISTS public.alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    prediction_id UUID REFERENCES public.risk_predictions(id) ON DELETE SET NULL,
    alert_type TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('LOW', 'WATCH', 'ELEVATED', 'CRITICAL')),
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_alerts_patient_status ON public.alerts(patient_id, status);

-- 8. Patient Timeline
CREATE TABLE IF NOT EXISTS public.patient_timeline (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID NOT NULL REFERENCES public.patients(id) ON DELETE CASCADE,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    event_type TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    severity TEXT NOT NULL DEFAULT 'LOW' CHECK (severity IN ('LOW', 'WATCH', 'ELEVATED', 'CRITICAL')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_timeline_patient_time ON public.patient_timeline(patient_id, timestamp DESC);

-- 9. Model Versions
CREATE TABLE IF NOT EXISTS public.model_versions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    model_name TEXT NOT NULL,
    version TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'Ready' CHECK (status IN ('Ready', 'Training', 'Deprecated')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- 10. Simulation Patients (Configurable ICU Scenarios)
CREATE TABLE IF NOT EXISTS public.simulation_patients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    patient_id UUID REFERENCES public.patients(id) ON DELETE CASCADE,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    trajectory_type TEXT NOT NULL,
    scenario_description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. System Events & Telemetry
CREATE TABLE IF NOT EXISTS public.system_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_name TEXT NOT NULL,
    event_source TEXT NOT NULL DEFAULT 'ML_SERVICE',
    payload JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_vitals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_labs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.risk_explanations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.patient_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.simulation_patients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_events ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Profiles: Users can read all clinical staff profiles, only update their own
CREATE POLICY "Profiles viewable by authenticated users" 
ON public.profiles FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = user_id);

-- Patients: Read access for authenticated staff; Insert/Update for staff
CREATE POLICY "Patients viewable by authenticated staff" 
ON public.patients FOR SELECT TO authenticated USING (true);

CREATE POLICY "Patients modifiable by authenticated staff" 
ON public.patients FOR ALL TO authenticated USING (true);

-- Patient Vitals
CREATE POLICY "Vitals viewable by authenticated staff" 
ON public.patient_vitals FOR SELECT TO authenticated USING (true);

CREATE POLICY "Vitals insertable by authenticated staff and services" 
ON public.patient_vitals FOR INSERT TO authenticated WITH CHECK (true);

-- Patient Labs
CREATE POLICY "Labs viewable by authenticated staff" 
ON public.patient_labs FOR SELECT TO authenticated USING (true);

CREATE POLICY "Labs insertable by authenticated staff and services" 
ON public.patient_labs FOR INSERT TO authenticated WITH CHECK (true);

-- Risk Predictions
CREATE POLICY "Predictions viewable by authenticated staff" 
ON public.risk_predictions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Predictions insertable by authenticated staff and ML" 
ON public.risk_predictions FOR INSERT TO authenticated WITH CHECK (true);

-- Risk Explanations
CREATE POLICY "Explanations viewable by authenticated staff" 
ON public.risk_explanations FOR SELECT TO authenticated USING (true);

-- Alerts
CREATE POLICY "Alerts viewable by authenticated staff" 
ON public.alerts FOR SELECT TO authenticated USING (true);

CREATE POLICY "Alerts modifiable by authenticated staff" 
ON public.alerts FOR ALL TO authenticated USING (true);

-- Timeline
CREATE POLICY "Timeline viewable by authenticated staff" 
ON public.patient_timeline FOR SELECT TO authenticated USING (true);

CREATE POLICY "Timeline insertable by authenticated staff" 
ON public.patient_timeline FOR INSERT TO authenticated WITH CHECK (true);

-- Model Versions
CREATE POLICY "Model versions viewable by authenticated staff" 
ON public.model_versions FOR SELECT TO authenticated USING (true);

-- Simulation Patients
CREATE POLICY "Simulation patients viewable by authenticated staff" 
ON public.simulation_patients FOR SELECT TO authenticated USING (true);

-- Enable Realtime for critical telemetry tables
ALTER PUBLICATION supabase_realtime ADD TABLE public.risk_predictions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.alerts;
ALTER PUBLICATION supabase_realtime ADD TABLE public.patient_vitals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.patient_timeline;
